sudo: required
language: go
go:
- master
env:
- DEP_VERSION="0.5.1"
before_install:
- curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64
  -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep
install:
- dep ensure
deploy:
  provider: releases
  api_key:
    secure: sXUtgHHTYClgpLk4Oiy/kQH9RRbtnyV0sxXOU1nsNgKm+gYkytLDnVQ24o5tch19EfdMjh8oU14grplCRMgxacTNGmjBaUFVvWW7z0PH973UIxp2A0V9FPoslDklYdcY4x26n1RA2gN8NM6pKSmkrDzTogIMZuu8ttN0vVir28RmBC5TrVHZopRW8aiUJhm8dLpEUyaV/Et5czb793xLzcgbIgdiunyRdxUzzehza0S7ivhiK6YR7LF5rulR52qnKBamrU1dTkO7ZjfvZz/alIULzgRh0YANGhLwqPoxQ+99VWqS+wP5L7DYVsJRmfY36Svjv39pEfz77/09ZTtHmgFkllWWMCbMvCF1WsvF5bIZoEZCLP5C0Zji/Uiq84gV+kEMxOwuFN2yXx77irJxJgensxox9GWH+5j2tHwitFNy5793Z0FmYd/V+BIvX+prcFPMGCDe/jCsG01xQqPhxPVWjKhNynuNu1E61iknjCsJb/Zg30Yd+kj1Hy53+zHfGCdjtltmIq0lCHFggPKB4nFOBBNXmaSecwj5Gnl6HXZAUcpyu7xuaZCF3kM71iB1OswNRT04Xfr7AV50dUm/X8hqKa9C0dhrWP8pStYppVGrdLoxpxFkbUVCTbF+BkvNw9z2NkEKrnER08pUjOmflVHoZRDp8P+H1VK3YR6G2j8=
  file_glob: true
  file: build/archive/*
  skip_cleanup: true
  on:
    repo: NoUseFreak/go-freeproxy
    tags: true
    branch: master
